name: Python IndexedTar pipeline

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r  requirements.txt
    - name: Lint with black and flake8
      run: |
        flake8 --max-line-length 120 indexedtar
        black --check indexedtar
    - name: Test with pytest
      run: |
        export PYTHONPATH="."; py.test --cov=indexedtar tests